### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by Luismm2311** [droidfirmwares/miflashtool#1]
Exception Text:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Desktop\MiFlash20220507\log\miflash@2024112.txt'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
at XiaoMiFlash.code.Utility.Log.w(String msg, Boolean throwEx)
at XiaoMiFlash.MainFrm.RefreshDevice()
at XiaoMiFlash.MainFrm.btnFlash_Click(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
Base Path: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
XiaoMiFlash
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
Base Path: file:///D:/Desktop/MiFlash20220507/XiaoMiFlash.exe
(Other assembly details continue in a similar format...)

JIT Debugging:
To enable Just-In-Time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
<system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the machine
rather than be handled by this dialog box.

**Comment by joseguzman1337** [comment]
Hello @Luismm2311 please find below the solution: 
1. Inside MiFlash20220507 folder, create a subfolder called **log**

**Comment by lucasliet** [comment]
> Hello [@Luismm2311](https://github.com/Luismm2311) please find below the solution:
> 
>     1. Inside MiFlash20220507 folder, create a subfolder called **log**

it worked for me, thanks!
